### ISSUE TITLE
TypeError('first argument must be a string or Buffer')

### ISSUE THREAD

**Issue by k33g** [restlet/restlet-framework-js#82]
Hello
I try to run helloWorld node sample [https://github.com/restlet/restlet-framework-js/blob/master/samples/node/helloworld/server.js](https://github.com/restlet/restlet-framework-js/blob/master/samples/node/helloworld/server.js)

I've got theses errors when I call [http://localhost:3000/helloworld/](http://localhost:3000/helloworld/) in my browser: (I've tested with node 0.10.13 and node 0.4.0, same errors)

    http.js:783
        throw new TypeError('first argument must be a string or Buffer');
              ^
    TypeError: first argument must be a string or Buffer
        at ServerResponse.OutgoingMessage.write (http.js:783:11)
        at Object.headers.fillHeadersAndContentInResponse (/Users/k33g_org/node_modules/restlet/lib/headers.js:396:17)
        at Object.response.end (/Users/k33g_org/node_modules/restlet/lib/server-utils.js:345:13)
        at Object.response.end (/Users/k33g_org/node_modules/restlet/lib/server.js:580:20)
        at Object.serverUtils.sendNotFound (/Users/k33g_org/node_modules/restlet/lib/server-utils.js:370:12)
        at Object.handle (/Users/k33g_org/node_modules/restlet/lib/server.js:499:21)
        at Object.handle (/Users/k33g_org/node_modules/restlet/lib/server.js:583:19)
        at handle (/Users/k33g_org/node_modules/restlet/lib/server.js:267:29)
        at Server.<anonymous> (/Users/k33g_org/node_modules/restlet/lib/server-transport.js:17:5)
        at Server.EventEmitter.emit (events.js:98:17)

Regards
Philippe

**Comment by templth** [comment]
Hello Philippe,

I just released a new version (the 0.4.1 one) with a set of fixes and improvments in unit tests. This version was publised in NPM so you can get it using an `npm install restlet`.

The hello world sample will now work. A small hint: we need to improve request handler selection not to be strict. For example, `*/*`, `application/*` and `application/*` would be accepted for JSON request handlers (currently only `application/json` matches). I mean you need to add an header `Accept` with value `application/json` if you need to serve JSON content. It's the case in the sample since the request handler is defined using the method `getJson`.

Feel free to tell me if you have more questions. Thanks for using / testing Restlet JS!
Thierry

**Comment by k33g** [comment]
Hello Thierry

now I can run sample without error, but if I call directly the url http://localhost:3000/helloworld from my browser I get this: "Method Not Allowed" and ok if I had header Accept to request with PostMan.
Fine
Thank you

**Comment by templth** [comment]
Hello Philippe,

Pleased to hear that it fixed your problem! We're working on improving the request handler selection at the moment... This will be integrated in the next version.

Thierry
